---
dist: bionic
language: ruby
cache: bundler

addons:
  apt:
    packages:
      - graphviz

rvm:
  - ruby-head
  - 2.6
  - 2.5
  - 2.4

before_install:
  - gem install bundler -v "~> 2.0"

install:
  - bundle install --jobs=3 --retry=3

matrix:
  allow_failures:
    - rvm: ruby-head
